/**
 * Honesty media copy — HM-00.
 *
 * Every string a honesty-media screen renders, keyed by the id it carries in
 * design/honesty-media/JOURNEYS-AND-COPY.md §9. That file is the source; this
 * one mirrors it, and tests/honesty-copy.test.ts fails when they drift in
 * either direction. Change the words there first.
 *
 * Why a flat map rather than nested objects: the id is the review handle. A
 * reviewer can grep `hm.badge.full` in the design doc, in this file and in the
 * component that renders it, and see the same words in all three places.
 *
 * House rules the sweep below enforces on every string: no blockchain,
 * crypto, wallet, web3, DAO, smart contract, on-chain or gas; no beautify,
 * enhance or generative language; no courtroom claims about location.
 */

/**
 * The policy version a host acknowledges before the first frame. Stored on
 * the scan row. Bump it when the host or guest disclosure changes in
 * substance (docs/honesty-media/POLICY.md), not for a typo.
 */
export const HONESTY_POLICY_VERSION = "1";

/** The rule a reviewer can quote. */
export const HONESTY_RULE = "stitch / stabilize / compress / cleanup only";

export const HM = {
  "hm.badge.short": "Geo-proven walkthrough",
  "hm.badge.full": "Geo-proven walkthrough · Captured by the host · Stitched, not invented",
  "hm.badge.captured": "Captured {date}",
  "hm.badge.scope.whole": "Whole home",
  "hm.badge.scope.partial": "Rental areas only",
  "hm.badge.a11y": "Geo-proven walkthrough. Captured by the host on {date}. Stitched from what the host recorded, not invented.",
  "hm.badge.processing": "Walkthrough in progress",
  "hm.badge.none": "No walkthrough yet",
  "hm.pin.title": "Where the front door is",
  "hm.pin.hint": "Drop the pin on your front door. Your honesty scan is checked against this spot.",
  "hm.pin.set": "Set the front door pin",
  "hm.pin.move": "Move the pin",
  "hm.pin.useLocation": "Use my location now",
  "hm.pin.useLocation.hint": "Stand at your front door with your phone. We use your phone's location, never your network.",
  "hm.pin.confirm.title": "Is this your front door?",
  "hm.pin.confirm.accuracy": "Your phone puts you within about {accuracy} m of here.",
  "hm.pin.confirm.yes": "Yes, set it here",
  "hm.pin.confirm.no": "No, let me move it",
  "hm.pin.saved": "Pin set.",
  "hm.pin.noFix": "We couldn't get a location fix. Try again outside, or drop the pin by hand.",
  "hm.pin.advanced": "Enter coordinates",
  "hm.pin.advanced.hint": "Decimal degrees, such as 40.7128, -74.0060.",
  "hm.pin.precision.legend": "What guests see on the map",
  "hm.pin.precision.area": "The neighborhood — an area about {area} m across, not the exact spot",
  "hm.pin.precision.exact": "The exact spot",
  "hm.pin.precision.note": "Guests with a confirmed stay always see the exact spot.",
  "hm.pin.required": "Set the front door pin first. Your honesty scan is checked against it.",
  "hm.pin.lat": "Latitude",
  "hm.pin.lng": "Longitude",
  "hm.pin.invalid": "Enter both latitude and longitude as decimal degrees, or leave both empty.",
  "hm.pin.roughFix": "That fix is too rough to use (about {accuracy} m). Try again outside, standing still, or enter the coordinates by hand.",
  "hm.pin.unsaved": "Save changes to set the pin.",
  "hm.pin.changeWarning": "Changing the pin takes down any honesty scan for this home. You'd scan again.",
  "hm.hub.title": "Honesty scan",
  "hm.hub.notStarted.title": "Not started",
  "hm.hub.notStarted.body": "Walk-scan your home from your phone while you're there. It takes one visit.",
  "hm.hub.start": "Scan from your phone",
  "hm.hub.desktop.title": "Scan from your phone",
  "hm.hub.desktop.body": "Recording needs your phone's camera and location. Sign in on your phone, open Your homes, choose this home, then Scan.",
  "hm.hub.desktop.email": "Email me the link",
  "hm.hub.desktop.emailed": "Sent to {email}.",
  "hm.hub.inProgress.title": "Walk in progress",
  "hm.hub.inProgress.body": "A walk was started on your phone and hasn't been finished. Continue it there, or delete it and start again.",
  "hm.hub.discard": "Delete this walk",
  "hm.hub.located.title": "Location confirmed at this home.",
  "hm.hub.located.body": "The recording is on the phone that made the walk, in the browser that recorded it. Open this page there and the upload starts on its own.",
  "hm.hub.facts": "Verified isn't published, isn't payouts, and isn't bookings open. Each is its own step.",
  "hm.editor.scan.title": "Honesty scan",
  "hm.editor.scan.body": "Before guests can book, walk-scan the home from your phone. The walk is checked against the front door pin.",
  "hm.editor.scan.cta": "Open the honesty scan",
  "hm.capture.unsupported": "This browser can't record in the page. Open this link in Safari or Chrome on your phone.",
  "hm.perm.camera.title": "Stead needs the camera to record the walk.",
  "hm.perm.camera.body": "Allow camera access in your browser settings, then try again.",
  "hm.perm.location.title": "Stead needs your location while you record.",
  "hm.perm.location.body": "It's how we prove the walk happened at this home. Allow location access, then try again.",
  "hm.perm.retry": "Try again",
  "hm.loc.good": "Location: good (about {accuracy} m)",
  "hm.loc.rough": "Location: rough (about {accuracy} m) — expected indoors",
  "hm.loc.none": "Location: no fix yet — step outside",
  "hm.loc.off": "Location: off — allow location to continue",
  "hm.capture.outsideStart.prompt": "Outside your front door? Turn slowly in a full circle.",
  "hm.capture.outsideStart.cta": "I'm outside — start",
  "hm.capture.turn.prompt": "Recording. Turn slowly in a full circle at your door, then walk in.",
  "hm.capture.walkIn": "Walk in",
  "hm.capture.waitingFix": "Waiting for a clearer location fix… Standing still helps.",
  "hm.capture.recording.prompt": "Walk every room slowly. Lights on. Take your time.",
  "hm.capture.pause": "Pause",
  "hm.capture.resume": "Resume",
  "hm.capture.paused": "Paused. Your location is still being recorded.",
  "hm.capture.background": "Recording paused when the app went to the background. Continue where you were.",
  "hm.capture.finishOutside": "Finish outside",
  "hm.capture.outsideEnd.prompt": "Back outside your front door? Turn slowly in a full circle, then finish.",
  "hm.capture.outsideEnd.cta": "Finish the walk",
  "hm.capture.stop": "Stop without finishing",
  "hm.capture.stop.title": "Delete this walk?",
  "hm.capture.stop.body": "A walk that doesn't end outside can't be verified. Nothing has been uploaded yet.",
  "hm.capture.stop.confirm": "Delete this walk",
  "hm.capture.stop.cancel": "Keep waiting",
  "hm.capture.awake": "Recording keeps the screen on. Plug in if you can.",
  "hm.capture.maxLength": "Walks up to {maxMinutes} minutes.",
  "hm.capture.elapsed": "{mm}:{ss}",
  "hm.capture.preparing": "Getting the camera ready…",
  "hm.capture.maxReached": "You've reached the {maxMinutes}-minute limit. Head back outside and finish the walk.",
  "hm.capture.submitting": "Sending the location record…",
  "hm.capture.submitFailed": "We couldn't send the location record. Try again when you're back online.",
  "hm.capture.interrupted.title": "This walk was interrupted.",
  "hm.capture.interrupted.body": "The recording didn't survive the reload. Delete this walk and start again from the door.",
  "hm.capture.notCurrent": "This walk isn't open any more.",
  "hm.upload.title": "Uploading your walk",
  "hm.upload.body": "Keep this page open. Wi-Fi is best.",
  "hm.upload.progress": "{done} of {total} uploaded",
  "hm.upload.group.video": "Video",
  "hm.upload.group.location": "Location record",
  "hm.upload.group.details": "Details",
  "hm.upload.pause": "Pause upload",
  "hm.upload.resume": "Resume upload",
  "hm.upload.stopped.title": "The upload stopped.",
  "hm.upload.stopped.body": "Nothing you recorded was lost. Resume when you're back online.",
  "hm.upload.tooLarge.title": "This walk is larger than we can accept.",
  "hm.upload.tooLarge.body": "{size} of {limit} allowed. Record a shorter walk — {maxMinutes} minutes at most.",
  "hm.upload.done": "Uploaded. Your walk is in the queue for reconstruction.",
  "hm.upload.checking": "Checking the location record",
  "hm.upload.located": "Location confirmed at this home.",
  "hm.upload.preparing": "Getting your walk ready to upload",
  "hm.upload.paused": "Paused. Nothing is lost.",
  "hm.upload.offline": "You're offline. The upload continues when you're back online.",
  "hm.upload.group.location.done": "Sent with the walk",
  "hm.upload.group.details.pending": "After the video",
  "hm.upload.completing": "Finishing up…",
  "hm.upload.unconfigured.title": "Uploads aren't set up on this deployment yet.",
  "hm.upload.unconfigured.body": "Your recording stays on this phone until they are.",
  "hm.upload.mismatch.title": "A part didn't arrive the way it left.",
  "hm.upload.mismatch.body": "We sent it again. If this keeps happening, delete the walk and scan again.",
  "hm.rejected.title": "This walk wasn't verified at this home.",
  "hm.rejected.geofence": "The location record puts this walk somewhere else. If the pin on your listing is wrong, fix the pin and scan again.",
  "hm.rejected.samples": "We didn't get enough location readings to verify the walk. Keep location on, and stand outside for a moment at the start and the end.",
  "hm.rejected.accuracy": "The location readings were too rough to verify. Start and finish outside, standing still for a few seconds.",
  "hm.rejected.bookends": "The walk didn't start and end outside the front door.",
  "hm.rejected.checkPin": "Check the pin",
  "hm.rejected.again": "Scan again",
  "hm.rejected.exif": "Photo location data is shown here for your reference. On its own it doesn't prove anything.",
  "hm.build.queued.title": "In the queue",
  "hm.build.queued.body": "Your walk is waiting for the reconstruction worker. This can take a while.",
  "hm.build.notify.email": "We'll email {email} when it's ready.",
  "hm.build.notify.none": "Check back here.",
  "hm.build.notYet": "Reconstruction isn't switched on yet. Your walk is safely uploaded and will be first in line when it is.",
  "hm.build.running.title": "Building the walkthrough",
  "hm.build.running.body": "We're stitching and steadying what you recorded. Nothing is added.",
  "hm.build.started": "Started {time}",
  "hm.build.eta": "About {minutes} minutes left",
  "hm.build.failed.title": "We couldn't build a walkthrough from this walk.",
  "hm.build.failed.tooFewFrames": "The walk was too short to build from.",
  "hm.build.failed.tooDark": "Large parts were too dark to match up. Try again with the lights on and curtains open.",
  "hm.build.failed.motionBlur": "Fast movement blurred too many frames. Walk slowly and keep the phone steady.",
  "hm.build.failed.pose": "We couldn't work out the camera's path through the home. Overlapping views help — pan slowly and revisit doorways.",
  "hm.build.failed.worker": "Something went wrong on our side. Nothing you recorded was lost.",
  "hm.build.failed.stills": "Here's what you recorded",
  "hm.build.retry": "Retry",
  "hm.build.again": "Scan again",
  "hm.build.ready.title": "Ready for you to mark private areas",
  "hm.build.ready.body": "Guests can't see the walkthrough until you've done this.",
  "hm.build.ready.cta": "Mark private areas",
  "hm.build.ready.whole": "Confirm whole home",
  "hm.verified.title": "Verified",
  "hm.verified.body": "Captured {date}. Guests can walk this home once it's published.",
  "hm.verified.view": "See it as a guest",
  "hm.verified.again": "Scan again",
  "hm.revoked.title": "Taken down",
  "hm.revoked.body": "This walkthrough was taken down on {date}: {reason}. Guests can't walk this home, and it can't take bookings, until a new walk is verified.",
  "hm.revoked.reason.pinChanged": "the front door pin was changed",
  "hm.mask.title": "What guests will see",
  "hm.mask.intro": "Mark anything private. It's cut out before guests see the walkthrough. We hide it — we don't paint over it or fill it in.",
  "hm.mask.tool.private": "Mark a private area",
  "hm.mask.tool.keep": "Keep only this area",
  "hm.mask.tool.door": "Place the front door",
  "hm.mask.tool.erase": "Remove this box",
  "hm.mask.tool.undo": "Undo",
  "hm.mask.view.top": "From above",
  "hm.mask.view.look": "Look around",
  "hm.mask.label.private": "Private — hidden from guests",
  "hm.mask.label.keep": "Rental area — the only part guests see",
  "hm.mask.whole.check": "Everything in this walk is part of the rental",
  "hm.mask.whole.hint": "Guests will see it all. You're confirming there are no private rooms in this walk.",
  "hm.mask.room.required": "A private room listing needs a \"Keep only this area\" box around the room guests rent. Shared spaces you want to show can be inside the box too.",
  "hm.mask.preview": "Preview as a guest",
  "hm.mask.finish": "Finish and verify",
  "hm.mask.finish.title": "Finish and verify?",
  "hm.mask.finish.body": "Anything inside a private box is removed from the guest walkthrough. You can change this later, but the walkthrough goes back through verification when you do.",
  "hm.mask.change.title": "Change what guests see?",
  "hm.mask.change.body": "Changing the mask takes the walkthrough down while we apply it. Guests can't walk this home, and it isn't bookable, until it's verified again.",
  "hm.mask.change.confirm": "Change the mask",
  "hm.mask.change.cancel": "Keep it as is",
  "hm.mask.saved": "Saved. Applying the change.",
  "hm.walk.section.title": "Walk through this home",
  "hm.walk.enter": "Walk through this home",
  "hm.walk.stills.title": "What the host recorded",
  "hm.walk.about": "How this walkthrough was made",
  "hm.walk.loading": "Loading the walkthrough… {loadedMb} of {totalMb} MB",
  "hm.walk.leave": "Leave the walk",
  "hm.walk.help": "How to move",
  "hm.walk.help.keys": "Move: W A S D or the arrow keys · Look: drag, or hold Shift with the arrow keys · Leave: Esc",
  "hm.walk.help.touch": "Move: drag on the left · Look: drag on the right · Leave: the ✕ at the top",
  "hm.walk.reset": "Reset view",
  "hm.walk.reducedMotion.title": "Showing stills",
  "hm.walk.reducedMotion.body": "Your device asks for less motion, so here are the host's recorded frames. The 3D walk only moves when you do.",
  "hm.walk.reducedMotion.start": "Start the 3D walk",
  "hm.walk.noWebgl.title": "This walkthrough needs a newer browser.",
  "hm.walk.noWebgl.body": "Here's what the host recorded instead.",
  "hm.walk.loadFailed": "We couldn't load the walkthrough.",
  "hm.walk.retry": "Try again",
  "hm.walk.notFound.title": "No walkthrough here.",
  "hm.walk.notFound.body": "This home may not have one yet, or the link is out of date.",
  "hm.walk.ownerPending.title": "Your walkthrough isn't ready yet.",
  "hm.walk.ownerPending.cta": "See its progress",
  "hm.walk.outside": "Go outside",
  "hm.walk.inside": "Go inside",
  "hm.walk.approach.title": "At the front door",
  "hm.walk.approach.body": "Recorded by the host at the start of the walk.",
  "hm.map.title": "Where it is",
  "hm.map.area": "Neighborhood shown. The exact spot is shared once your stay is confirmed.",
  "hm.map.exact": "Exact location, shared by the host.",
  "hm.map.attribution.host": "Recorded by the host",
  "hm.map.attribution.third": "Street imagery from {source} contributors, not the host",
  "hm.map.noImagery": "No street imagery here yet.",
  "hm.explore.walkCity": "Walk {city}",
  "hm.nbhd.title": "Walk {city}",
  "hm.nbhd.subtitle": "Real streets, real Stead homes. Pins are homes with a geo-proven walkthrough.",
  "hm.nbhd.nearby": "Homes on Stead near this view",
  "hm.nbhd.nearby.none": "No Stead homes near this view.",
  "hm.nbhd.empty.title": "No geo-proven homes in {city} yet.",
  "hm.nbhd.empty.body": "Nothing here is made up. When a host in {city} completes a walkthrough, it appears here.",
  "hm.nbhd.map": "Map",
  "hm.nbhd.street": "Street",
  "hm.nbhd.open": "Walk through this home",
  "hm.check.title": "Ready to publish?",
  "hm.check.details": "Details",
  "hm.check.details.done": "Complete",
  "hm.check.photos": "Photos",
  "hm.check.photos.count": "{n} added",
  "hm.check.photos.none": "None yet — optional, but a home with no photos is a hard sell",
  "hm.check.scan": "Honesty scan",
  "hm.check.payouts": "Payouts",
  "hm.check.payouts.note": "Separate — needed before a guest can pay, not before publishing.",
  "hm.check.publishBlocked": "Publish when your honesty scan is verified. Guests can't book a home without one.",
  "hm.check.platformClosed": "Guest bookings on Stead aren't open yet. Publishing lists your home; bookings open later.",
  "hm.scan.state.notStarted": "Scan: Not started",
  "hm.scan.state.needsPin": "Scan: Needs the front door pin",
  "hm.scan.state.capturing": "Scan: Walk in progress",
  "hm.scan.state.located": "Scan: Location confirmed",
  "hm.scan.state.uploading": "Scan: Uploading",
  "hm.scan.state.checking": "Scan: Checking location",
  "hm.scan.state.rejected": "Scan: Not verified",
  "hm.scan.state.queued": "Scan: In the queue",
  "hm.scan.state.building": "Scan: Building",
  "hm.scan.state.failed": "Scan: Couldn't build",
  "hm.scan.state.needsMask": "Scan: Mark private areas",
  "hm.scan.state.verified": "Scan: Verified",
  "hm.scan.state.revoked": "Scan: Taken down",
  "hm.scan.next.start": "Scan from your phone",
  "hm.scan.next.pin": "Set the front door pin",
  "hm.scan.next.continue": "Continue on your phone",
  "hm.scan.next.resume": "Resume upload",
  "hm.scan.next.why": "See why",
  "hm.scan.next.progress": "See progress",
  "hm.scan.next.mask": "Mark private areas",
  "hm.scan.next.view": "See it as a guest",
  "hm.book.notVerified.title": "This home isn't open for stays yet.",
  "hm.book.notVerified.body": "The host still needs a verified walkthrough. You can read the home and message the host.",
  "hm.book.notVerified.back": "Back to the home",
  "hm.sheet.title": "Before you start the walk",
  "hm.sheet.record.heading": "What we record",
  "hm.sheet.record.video": "Video from your phone's camera while you walk.",
  "hm.sheet.record.location": "Your phone's location, continuously, while you record.",
  "hm.sheet.why.heading": "Why the location",
  "hm.sheet.why.body": "To prove this walk happened at this home. Guests see that it was proven, and the date. They never see your route.",
  "hm.sheet.video.heading": "What we do with the video",
  "hm.sheet.video.body": "We stitch, steady, and compress it into a walkthrough guests can move through. We don't add rooms, furniture, or views, and we don't tidy anything up. What you record is what guests see.",
  "hm.sheet.private.heading": "Private areas",
  "hm.sheet.private.body": "After the walk, you mark anything private. It's cut out before anyone else sees the walkthrough.",
  "hm.sheet.bookings.heading": "Bookings",
  "hm.sheet.bookings.body": "A home can't take bookings until its walkthrough is verified.",
  "hm.sheet.tips.heading": "Tips",
  "hm.sheet.tips.body": "Start outside your front door and turn slowly in a full circle. Walk every room you want guests to see, slowly, with the lights on. Finish outside your front door the same way.",
  "hm.sheet.acknowledge": "I've read this and I'm at the home now.",
  "hm.sheet.acknowledge.hint": "Tick the box to continue.",
  "hm.sheet.start": "Start the walk",
  "hm.sheet.notNow": "Not now",
  "hm.sheet.starting": "Starting…",
  "hm.sheet.failed": "We couldn't start the walk. Try again.",
  "hm.sheet.policyChanged": "The honesty policy changed. Read it again before you start.",
  "hm.about.title": "How this walkthrough was made",
  "hm.about.recorded": "The host recorded this walk on their phone, at this home. Their phone reported its location the whole time, within {radius} m of the listing's front door pin, and the walk started and ended outside the front door.",
  "hm.about.stitched": "We stitched, steadied, and compressed what they recorded. We didn't add rooms, furniture, or views. If something wasn't recorded, it isn't here.",
  "hm.about.scope.whole": "Whole home. Everything you can walk is part of the rental.",
  "hm.about.scope.partial": "Rental areas only. Private rooms are left out on purpose.",
  "hm.about.captured": "Captured {date}. This is a record of that day, not a live feed.",
  "hm.about.nearby": "Nearby pins are other Stead homes with a geo-proven walkthrough. Nothing on the map is made up.",
  "hm.about.signal": "Location proof is a strong signal, not a guarantee.",
} as const;

export type HmId = keyof typeof HM;

/**
 * Fill `{placeholders}` from the design doc with values the server supplied.
 * An unknown placeholder is left visible rather than silently blanked, so a
 * missing value shows up in review instead of reading as a finished sentence.
 */
export function hm(id: HmId, vars: Record<string, string | number> = {}): string {
  return HM[id].replace(/\{(\w+)\}/g, (match, key: string) =>
    Object.prototype.hasOwnProperty.call(vars, key) ? String(vars[key]) : match,
  );
}

/** The badge, locked. Compact on cards, full on detail and in the disclosure. */
export const HONESTY_BADGE = {
  short: HM["hm.badge.short"],
  full: HM["hm.badge.full"],
} as const;

/**
 * Words that never appear in product copy, swept across every string above.
 * Lower-case; matched as whole words or phrases, case-insensitively.
 */
export const HONESTY_BANNED_TERMS = [
  // House bans (CLAUDE.md copy rules).
  "blockchain",
  "crypto",
  "wallet",
  "web3",
  "dao",
  "smart contract",
  "on-chain",
  "gas",
  // Honesty bans: reconstruction verbs and features that invent.
  "beautify",
  "beautified",
  "enhance",
  "enhanced",
  "retouch",
  "declutter",
  "auto-fix",
  "magic",
  "reimagine",
  "upscale",
  "virtual staging",
  "inpaint",
  "generative",
  // Provenance claims the badge must never make.
  "gps-certified",
  "tamper-proof",
  "court-admissible",
  "hardware attestation",
  "100% real",
  "live now",
] as const;

/**
 * Control labels that must not exist even disabled or in a tooltip. Kept as
 * data so the copy test can assert no string is one of them, and so a later
 * lint can read the same list.
 */
export const HONESTY_BANNED_CONTROL_LABELS = [
  "Enhance",
  "Beautify",
  "Retouch",
  "Tidy",
  "Declutter",
  "Complete the room",
  "Fill",
  "Auto-fix",
  "Magic",
  "Clean up",
  "Generate",
  "Reimagine",
  "Stage",
  "Virtual staging",
  "Render",
  "Upscale",
  "Restore",
  "Smart erase",
  "Remove object",
] as const;
